name: action

on:
  push:
    branches:
      - deploy

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: core

      - name: Configure Git
        run: |
          git config --global user.name "이재민"
          git config --global user.email "cytor@naver.com"

      - name: Install rsync
        run: sudo apt-get install rsync

      - name: Configure merge strategy for pull
        run: git config --global pull.rebase false

      - name: Sync to Gitlab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git clone --branch core https://oauth2:$GITLAB_TOKEN@lab.ssafy.com/s10-bigdata-recom-sub2/S10P22D204.git S10P22D204
          mkdir -p S10P22D204/core
          rsync -av --delete --exclude='.git/' --exclude='.github/' ./core/ S10P22D204/core/
          cd S10P22D204
          git add core/
          git_status=$(git status --porcelain)
          if [ ! -z "$git_status" ]; then
            git commit -m "core server develop update"
            git push origin core --force
          else
            echo "No changes to commit."
          fi

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/core
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            MONGODB_URL=${{ secrets.MONGODB_URL }}
            GCP_SERVICE_ACCOUNT_JSON=${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
            ES_URL=${{ secrets.ES_URL }}
            ES_PASSWORD=${{ secrets.ES_PASSWORD }}
            ES_CERT_FINGERPRINT=${{ secrets.ES_CERT_FINGERPRINT }}
            ES_IDX_NAME=${{ secrets.ES_IDX_NAME }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop core || true
            docker rm core || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/core:latest
            docker run --name core -d \
            -p 8000:8000 \
            --network=bridge \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/core
            docker container prune -f
            docker image prune -f
