name: action

on:
  push:
    branches:
      - deploy

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "이재민"
          git config --global user.email "cytor@naver.com"

      - name: Install rsync
        run: sudo apt-get install rsync

      - name: Configure merge strategy for pull
        run: git config --global pull.rebase false

      - name: Sync to Gitlab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git clone https://oauth2:$GITLAB_TOKEN@lab.ssafy.com/s10-bigdata-recom-sub2/S10P22D204.git
          cd S10P22D204
          git checkout core || git checkout -b core
          git pull origin core
          mkdir -p core
          rsync -av --exclude='.git/' --exclude='.github/' ./ /tmp/S10P22D204/core/ || rsync_exit_code=$? 
          git add .
          git commit -m "core server develop update"
          git push origin core --force

